
#BACKGROUNDS FOR CHAPTER 2
image bg hopposHut = "raw assets/Chapter 2/Backgrounds/hoppos-hut-final.png"
image bg froggoStreet = "raw assets/Chapter 2/Backgrounds/froggo-street.png"
image bg mineStreet = "raw assets/Chapter 2/Backgrounds/mine-street.png"
image bg level_1_1 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 1/first_level_1.png"
image bg level_1_storage_room = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 1/level-1-storage-room.png"
image bg level_1_2 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 1/first_level_2.png"
image bg level_1_3 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 1/second_level_entance.png"
image bg level_2_1 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_2.png"
image bg level_2_2 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_3.png"
image bg level_2_3 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_4.png"
image bg level_2_4 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_6.png"
image bg level_2_5 = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_7.png"
image bg spotty_room = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_8.png"
image bg spotty_room_reversed = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_8_reversed.png"
image bg climb_room = "raw assets/Chapter 2/Backgrounds/Dino Nuggy Mine/Level 2/second_level_9.png"
image bg froggert_pub = "raw assets/Chapter 2/Backgrounds/froggert-bar-inside.png"
image bg elder_office = "raw assets/Chapter 2/Backgrounds/elders-office.png"